package com.tweetapp.model;

import java.util.List;



import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Builder;

@DynamoDBTable(tableName = "tweets")
@Builder
public class Tweet {
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
    private String username;
	
    private String email;
    @DynamoDBAttribute
    private String tweetDes;
    @DynamoDBAttribute
    private String date;
    @DynamoDBAttribute
    private int like;
    @DynamoDBAttribute
    private int dislike;
    @DynamoDBAttribute
    private List<Reply> replies;
    
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
    
	public String getTweetDes() {
		return tweetDes;
	}
	public void setTweetDes(String tweetDes) {
		this.tweetDes = tweetDes;
	}
	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	
	
	public int getLike() {
		return like;
	}
	public void setLike(int like) {
		this.like = like;
	}
	
	
	
	

	public int getDislike() {
		return dislike;
	}
	public void setDislike(int dislike) {
		this.dislike = dislike;
	}
	public List<Reply> getReplies() {
		return replies;
	}
	public void setReplies(List<Reply> replies) {
		this.replies = replies;
	}
	public Tweet() {
		super();
	}
	public Tweet(String id, String username, String email, String tweets, String date, int like, int dislike,
			List<Reply> replies) {
		super();
		this.id = id;
		this.username = username;
		this.email = email;
		this.tweetDes = tweets;
		this.date = date;
		this.like = like;
		this.dislike = dislike;
		this.replies = replies;
	}
	@Override
	public String toString() {
		return "Tweet [username=" + username + ", email=" + email + ", tweets=" + tweetDes + ", date=" + date + ", like="
				+ like + ", dislike=" + dislike + ", replies=" + replies + "]";
	}
	
	

	
	
	
	
    
    

}
